---
name: PART3 - CH1 - Step Output 1
on: workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: generate-random-id
        name: Generate random string
        # random_id를 key값으로 하는 value $RANDOM을 GITHUB_OUTPUT에 넣음
        # GITHUB_OUTPUT은 GIT에서 기본 제공
        run: echo "random_id=$RANDOM" >> "$GITHUB_OUTPUT"
      - id: build-project
        name: Build project
        # step의 id로 접근, outputs.key 값으로 접근 가능
        run: |
          echo "Random ID: ${{ steps.generate-random-id.outputs.random_id }}"
      - id: run-tests
        name: Run tests
        run: |
          echo "Random ID: ${{ steps.generate-random-id.outputs.random_id }}"
